version: '3'
services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db"
    
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file: ./.env

    environment:
      DB_PORT: 5432
      HOST: postgres
      USER: "postgres"
      PASSWORD: "postgres"
      DATABASE: "postgres"

    

volumes:
  pgdata: